title: Lucy Wright
logo: /assets/img/favicon-32x32.png
email: lucy.wright@bristol.ac.uk
description: Lucy Wright home page.
favicon: true
color-scheme: auto

remote_theme: vaibhavvikas/jekyll-theme-minimalistic
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme
platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/vaibhavvikas
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/vaibhavvikas

navigation:
  - name: Home page
    link: ./index.html
    sublist:
      - name: About Me
        link: ./index.html#aboutme
      - name: Education
        link: ./index.html#education
  - name: Conferences
    link: ./conferences.html
